version: '3.9'

services:
  mysql-master:
    image: bitnami/mysql:8.0
    volumes:
      - mysql-master:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
  mysql-slave:
    image: bitnami/mysql:8.0
    volumes:
      - mysql-slave:/bitnami/mysql/data
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_DATABASE=my_database
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password

volumes:
  mysql-master:
  mysql-slave:
