version: '3.9'

networks:
  network_default:
    external: true
  

services:      
  # Core services
  chrome:
    image: hub.hamdocker.ir/selenium/standalone-chrome
    restart: always
    networks:
      - network_default
    shm-size: 2g
    labels:
        traefik.enable: true
        traefik.http.routers.chrome.rule: Host(`chrome.mncdf.ir`)
        traefik.http.routers.chrome.service: selenium-chrome
        traefik.http.routers.chrome.entrypoints: websecure
        traefik.http.routers.chrome.tls.certresolver: myresolver
        traefik.http.services.selenium-chrome.loadbalancer.server.port: 4444
